/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppAppIndexImport } from './routes/_app/app/index'
import { Route as AppAppNotesNewImport } from './routes/_app/app/notes/new'
import { Route as AppAppNotesIdEditImport } from './routes/_app/app/notes/$id.edit'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppAppIndexRoute = AppAppIndexImport.update({
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)

const AppAppNotesNewRoute = AppAppNotesNewImport.update({
  path: '/app/notes/new',
  getParentRoute: () => AppRoute,
} as any)

const AppAppNotesIdEditRoute = AppAppNotesIdEditImport.update({
  path: '/app/notes/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/app/notes/new': {
      id: '/_app/app/notes/new'
      path: '/app/notes/new'
      fullPath: '/app/notes/new'
      preLoaderRoute: typeof AppAppNotesNewImport
      parentRoute: typeof AppImport
    }
    '/_app/app/notes/$id/edit': {
      id: '/_app/app/notes/$id/edit'
      path: '/app/notes/$id/edit'
      fullPath: '/app/notes/$id/edit'
      preLoaderRoute: typeof AppAppNotesIdEditImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppNotesNewRoute: typeof AppAppNotesNewRoute
  AppAppNotesIdEditRoute: typeof AppAppNotesIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppNotesNewRoute: AppAppNotesNewRoute,
  AppAppNotesIdEditRoute: AppAppNotesIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/app': typeof AppAppIndexRoute
  '/app/notes/new': typeof AppAppNotesNewRoute
  '/app/notes/$id/edit': typeof AppAppNotesIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/app': typeof AppAppIndexRoute
  '/app/notes/new': typeof AppAppNotesNewRoute
  '/app/notes/$id/edit': typeof AppAppNotesIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/app/notes/new': typeof AppAppNotesNewRoute
  '/_app/app/notes/$id/edit': typeof AppAppNotesIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/app' | '/app/notes/new' | '/app/notes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/app' | '/app/notes/new' | '/app/notes/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/app/'
    | '/_app/app/notes/new'
    | '/_app/app/notes/$id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/app/",
        "/_app/app/notes/new",
        "/_app/app/notes/$id/edit"
      ]
    },
    "/_app/app/": {
      "filePath": "_app/app/index.tsx",
      "parent": "/_app"
    },
    "/_app/app/notes/new": {
      "filePath": "_app/app/notes/new.tsx",
      "parent": "/_app"
    },
    "/_app/app/notes/$id/edit": {
      "filePath": "_app/app/notes/$id.edit.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
